language: node_js
sudo: false

node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm install codecov -g
after_success:
  - codecov
  